insert into RESULTADO values (1, 'CEF', 'CONTACTO EFECTIVO');
insert into RESULTADO values (2, 'CNE', 'CONTACTO NO EFECTIVO');
insert into RESULTADO values (3, 'NOC', 'NO CONTACTO');
insert into RESULTADO values (4, 'NOG', 'NO GESTIONADO');

INSERT INTO MOTIVO VALUES (1, '0101', 'PREVENTA', 1);
INSERT INTO MOTIVO VALUES (1, '0201', 'CONTACTO CON TERCEROS', 2);
INSERT INTO MOTIVO VALUES (1, '0101', 'PREVENTA', 1);